### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by fuad44**

### CODE REVIEW

**Comment by Pranav-Saraswat** [comment]
Do this shit in your fork repo not in this repo

**Comment by Amritraj2008** [comment]
@Hunter-XD Oho

**Comment by Amritraj2008** [comment]
@Amritraj2008 😅😅😅

**Comment by TechShreyash** [comment]
Wah bete moj kardi

**Comment by Amritraj2008** [comment]
@TechShreyash Huu

**Pull request closed without merging**
